https://leetcode.com/problems/combinations/

# Solution 1

In [36]:
import numpy as np

class Solution:
    
    def combine(self, n, k):
        
        # first k elements
        vals = np.arange(k) + 1
        yield np.copy(vals)

        while vals[0] <= n - k:
            for i, val in enumerate(vals[::-1]):
                # find first element from the end...
                # which can be updated
                if val < n - i:
                    break

            vals[-i-1:] = np.arange(val, val+i+1) + 1
            yield np.copy(vals)

In [37]:
n, k = 5, 3

list(Solution().combine(n, k))

[array([1, 2, 3]),
 array([1, 2, 4]),
 array([1, 2, 5]),
 array([1, 3, 4]),
 array([1, 3, 5]),
 array([1, 4, 5]),
 array([2, 3, 4]),
 array([2, 3, 5]),
 array([2, 4, 5]),
 array([3, 4, 5])]

In [38]:
n, k = 40, 5

%timeit list(Solution().combine(n, k))

4.02 s ± 58.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Solution 2

In [39]:
from itertools import combinations

class Solution:
    def combine(self, n, k):
        return combinations(range(1, n+1), k) 

In [40]:
n, k = 5, 3

list(Solution().combine(n, k))

[(1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 3, 4),
 (1, 3, 5),
 (1, 4, 5),
 (2, 3, 4),
 (2, 3, 5),
 (2, 4, 5),
 (3, 4, 5)]

In [41]:
n, k = 40, 5

%timeit list(Solution().combine(n, k))

76.7 ms ± 3.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
